/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import domainModel.DeGiay;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import service.IDeGiayService;
import service.impl.DeGiayServiecImpl;
import utilities.Utility;

/**
 *
 * @author admin
 */
public class ViewDeGiay extends javax.swing.JFrame {

    /**
     * Creates new form ViewDeGiay
     */
    private IDeGiayService deGiayService= new DeGiayServiecImpl();
    private utilities.Utility uti = new Utility();
    public ViewDeGiay() {
        initComponents();
        setLocationRelativeTo(null);
        loadTable(null);
    }

    private String click;
    public void loadTable(String input){
        DefaultTableModel mol = (DefaultTableModel) tbl_deGiay.getModel();
        mol.setRowCount(0);
        int stt = 1;
        for (var x : deGiayService.getAll(input)) {
            mol.addRow(new Object[]{
                stt++,
                x.getId(),
                x.getMa(),
                x.getTen()
            });
        }
    }
    
    public DeGiay getForm(){
        return new DeGiay(null, txt_ma.getText(), txt_ten.getText());
    }
    
    public boolean CheckDL(){
        if (uti.CheckRong(txt_ma.getText())) {
            JOptionPane.showMessageDialog(this, "Mã không được để trống");
            txt_ma.requestFocus();
            txt_ma.setText("");
            return true;
        }
        if (uti.CheckRong(txt_ten.getText())) {
            JOptionPane.showMessageDialog(this, "Tên không được để trống");
            txt_ten.requestFocus();
            txt_ten.setText("");
            return true;
        }
        return false;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_deGiay = new javax.swing.JTable();
        lbl_ten = new javax.swing.JLabel();
        txt_ma = new javax.swing.JTextField();
        lbl_ma = new javax.swing.JLabel();
        txt_ten = new javax.swing.JTextField();
        btn_them = new javax.swing.JButton();
        btn_sua = new javax.swing.JButton();
        btn_xoa = new javax.swing.JButton();
        btn_clear = new javax.swing.JButton();
        txt_tiemKiem = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbl_deGiay.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "STT", "ID", "Mã", "Tên"
            }
        ));
        tbl_deGiay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_deGiayMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_deGiay);

        lbl_ten.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_ten.setText("Tên Đế Giày");

        lbl_ma.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_ma.setText("Mã Đế Giày");

        btn_them.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_them.setText("Thêm");
        btn_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themActionPerformed(evt);
            }
        });

        btn_sua.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_sua.setText("Sửa");
        btn_sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_suaActionPerformed(evt);
            }
        });

        btn_xoa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_xoa.setText("Xóa");
        btn_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaActionPerformed(evt);
            }
        });

        btn_clear.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_clear.setText("Clear");
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });

        txt_tiemKiem.setText("Tìm Kiếm...");
        txt_tiemKiem.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txt_tiemKiemCaretUpdate(evt);
            }
        });
        txt_tiemKiem.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_tiemKiemFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_tiemKiemFocusLost(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(lbl_ma, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_ma, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(lbl_ten, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(txt_ten, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(136, Short.MAX_VALUE)
                .addComponent(btn_them, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(btn_sua, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(btn_xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(btn_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(134, 134, 134))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_tiemKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_ma, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_ma, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_ten, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_ten, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_them, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_sua, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(txt_tiemKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themActionPerformed
        // TODO add your handling code here:
        if (CheckDL()==false) {
            var temp = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn thêm mới");
        if (temp == 0) {
            JOptionPane.showMessageDialog(this, deGiayService.add(getForm()));
        loadTable(null);
        }else{
            loadTable(null);
        }
        }
        
    }//GEN-LAST:event_btn_themActionPerformed

    private void tbl_deGiayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_deGiayMouseClicked
        // TODO add your handling code here:
        var dong = tbl_deGiay.getSelectedRow();
        click = tbl_deGiay.getModel().getValueAt(dong, 1).toString();      
        txt_ma.setText(tbl_deGiay.getModel().getValueAt(dong, 2).toString());
        txt_ten.setText(tbl_deGiay.getModel().getValueAt(dong, 3).toString());
    }//GEN-LAST:event_tbl_deGiayMouseClicked

    private void btn_suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_suaActionPerformed
        // TODO add your handling code here:
        if (CheckDL()==false) {
            var temp = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn sửa thông tin không ?");
        if (temp == 0) {
            var deGiay = getForm();       
        deGiay.setId(click);
        JOptionPane.showMessageDialog(this, deGiayService.update(deGiay));
        loadTable(null);
        }
        else{
            loadTable(null);
        }
        }
    }//GEN-LAST:event_btn_suaActionPerformed

    private void btn_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaActionPerformed
        // TODO add your handling code here:
        var deGiay = new DeGiay();
        deGiay.setId(click);
        JOptionPane.showMessageDialog(this, deGiayService.delete(deGiay));
        loadTable(null);
    }//GEN-LAST:event_btn_xoaActionPerformed

    private void txt_tiemKiemFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_tiemKiemFocusGained
        // TODO add your handling code here:
        txt_tiemKiem.setText("");
        
    }//GEN-LAST:event_txt_tiemKiemFocusGained

    private void txt_tiemKiemFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_tiemKiemFocusLost
        // TODO add your handling code here:
        txt_tiemKiem.setText("Tìm Kiếm...");
        loadTable(null);
    }//GEN-LAST:event_txt_tiemKiemFocusLost

    private void txt_tiemKiemCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txt_tiemKiemCaretUpdate
        // TODO add your handling code here:
        if (txt_tiemKiem.getText().isEmpty()) {
            loadTable(null);
        }
        loadTable(txt_tiemKiem.getText());
    }//GEN-LAST:event_txt_tiemKiemCaretUpdate

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        // TODO add your handling code here:
        txt_ma.setText("");
        txt_ten.setText("");
    }//GEN-LAST:event_btn_clearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewDeGiay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewDeGiay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewDeGiay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewDeGiay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewDeGiay().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_sua;
    private javax.swing.JButton btn_them;
    private javax.swing.JButton btn_xoa;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_ma;
    private javax.swing.JLabel lbl_ten;
    private javax.swing.JTable tbl_deGiay;
    private javax.swing.JTextField txt_ma;
    private javax.swing.JTextField txt_ten;
    private javax.swing.JTextField txt_tiemKiem;
    // End of variables declaration//GEN-END:variables
}
